# 
apiVersion: v1
kind: Service
metadata:
  name: consul-server-service
  labels:
    app: consul
spec:
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: dns
      port: 8600
      targetPort: 8600
  selector:
    app: consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:1.15
        args:
          - "agent"
          - "-dev"
          - "-client=0.0.0.0"
        ports:
          - containerPort: 8500
            name: http
          - containerPort: 8600
            name: dns
        env:
          - name: CONSUL_BIND_ADDR
            value: "0.0.0.0"