apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
      - name: translator-container
        image: masterhuthiu/movie-translator:latest
        imagePullPolicy: Always
        env:
        - name: CONSUL_HOST
          value: "consul-server-service" # Tên service của Consul trong K8s
        - name: CONSUL_PORT
          value: "8500"
        envFrom:
        - secretRef:
            name: ai-secrets