# 1. Tạo Secret (Đã dùng Key bạn cung cấp)
kubectl create secret generic ai-secrets \
  --from-literal=GEMINI_API_KEY='AIzaSyCHYvBTr8nsPIOeg-uxJZs5O9xxWsnodog' \
  --from-literal=MONGO_URI='mongodb://mongodb-service:27017/sample_mflix'

# 2. Deploy bản chuẩn hóa Port 8080
cat <<EOF > final-fix.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
      - name: translator-container
        image: masterhuthiu/movie-translator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: ai-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: translator-entrypoint
spec:
  selector:
    app: translator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
EOF

kubectl apply -f final-fix.yml